name: CI

on:
  push:
    branches: 
      - master

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '11.x'
    - name: Install Dependencies
      run: yarn
    - name: Test implementation
      run: yarn test
